
import React from 'react';

const TermsAndConditions: React.FC = () => {
  return (
    <div className="container mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold mb-8 text-earth-900">Terms & Conditions – Flow 83</h1>
      
      <div className="prose max-w-none text-earth-800 space-y-6">
        <p>
          Welcome to Flow 83. By accessing and using this platform, you agree to the following terms and conditions. Please read them carefully before beginning any journey.
        </p>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-earth-800">1. Purpose of the Platform</h2>
          <p>
            Flow 83 offers AI-guided personal growth journeys designed to support emotional clarity, mindset development, and spiritual or self-awareness expansion. The platform provides structured, daily reflections and exercises based on each user's selected path.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-earth-800">2. AI-Based Guidance</h2>
          <p>
            All feedback, guidance, and conversational responses on Flow 83 are generated by an artificial intelligence system. While the system is built to simulate emotionally supportive communication, it is not operated by a licensed therapist, coach, or mental health professional.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-earth-800">3. No Guarantee of Results</h2>
          <p>
            Every individual's experience is unique. Flow 83 makes no promises regarding specific results, personal breakthroughs, or emotional or spiritual outcomes. Results may vary based on personal context, engagement, and interpretation.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-earth-800">4. Not a Substitute for Professional Help</h2>
          <p>
            The platform is not a medical, psychological, or therapeutic service. It is not intended to diagnose, treat, or replace mental health services or professional coaching. If you are in emotional distress or crisis, please seek support from a licensed professional or local emergency services.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-earth-800">5. Personal Responsibility</h2>
          <p>
            By using Flow 83, you accept full responsibility for your actions, emotional responses, and decisions made during or following your engagement with the platform. You understand that your use of the platform is entirely voluntary and at your own discretion.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-earth-800">6. Privacy & Data Usage</h2>
          <p>
            We value your privacy. By using Flow 83, you consent to the storage and processing of your responses and interactions with the AI to personalize and improve your experience. Your data will never be sold or shared with third parties without your consent.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-earth-800">7. Intellectual Property</h2>
          <p>
            All content, methods, user journeys, visuals, and AI logic on Flow 83 are the exclusive property of the platform and its creators. No content may be reproduced, copied, distributed, or used for commercial purposes without prior written permission.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-earth-800">8. Age Restriction</h2>
          <p>
            This platform is intended for users who are 18 years of age or older. By accessing or using Flow 83, you confirm that you meet this age requirement.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-earth-800">9. Cancellation & Refund Policy</h2>
          <p>
            Due to the digital and personalized nature of our content, all purchases are final and non-refundable. If you experience a technical issue or require support, please contact us directly.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-earth-800">10. Platform Availability & Changes</h2>
          <p>
            Flow 83 reserves the right to update, change, or discontinue any part of the platform, including features, services, or user journeys, at any time without prior notice.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-earth-800">11. User Conduct</h2>
          <p>
            Users are expected to engage respectfully and ethically with the platform. Any attempt to abuse, exploit, or manipulate the system — including spamming, offensive language, or disrupting the AI — may result in restricted access or account suspension.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4 text-earth-800">12. Contact</h2>
          <p>
            If you have questions, feedback, or need support regarding these terms, you may contact us at:
            <a href="/contact" className="text-spirit-600 hover:underline ml-1">our Contact page</a>.
          </p>
        </section>
        
        <section>
          <p className="font-semibold mt-8">
            By continuing to use Flow 83, you acknowledge that you have read, understood, and agreed to these Terms.
          </p>
        </section>
        
        <section>
          <p className="text-sm text-earth-600 mt-8">
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </section>
      </div>
    </div>
  );
};

export default TermsAndConditions;
