// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmomnhqbzeomjwbtssbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imptb21uaHFiemVvbWp3YnRzc2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NzE2MjcsImV4cCI6MjA2MjU0NzYyN30.TBtLgFe64pyE0Qro0ScjL64qAe-oaqyq3oY-as70id4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);